import argparse
import json
import re
import urllib.request
from datetime import datetime, timezone


def clamp(value, minimum, maximum):
    return max(minimum, min(maximum, value))


def load_json(path):
    with open(path, "r", encoding="utf-8-sig") as handle:
        return json.load(handle)


def call_ollama(prompt, model):
    payload = json.dumps({
        "model": model,
        "prompt": prompt,
        "stream": False,
        "options": {
            "temperature": 0.1
        }
    }).encode("utf-8")

    request = urllib.request.Request(
        "http://localhost:11434/api/generate",
        data=payload,
        headers={"Content-Type": "application/json"},
        method="POST",
    )

    with urllib.request.urlopen(request, timeout=180) as response:
        result = json.loads(response.read().decode("utf-8"))

    text = result.get("response", "").strip()

    # Accept either plain JSON or JSON wrapped in markdown/code fences.
    match = re.search(r"\{.*\}", text, re.DOTALL)
    if not match:
        raise RuntimeError("Ollama did not return a JSON object.")

    return json.loads(match.group(0))


def deterministic_risk(comparison, telemetry):
    score = 0
    reasons = []
    hard_failures = []

    green = telemetry["green"]
    blue = telemetry["blue"]
    regressions = comparison["regressions"]

    if comparison.get("technicalGate") != "PASS":
        reasons.append(
            "One or more Green-vs-Blue reference thresholds were exceeded; "
            "this is supporting risk evidence for AI evaluation, not a hard safety failure."
        )

    if green["readyPods"] < green["expectedReplicas"]:
        hard_failures.append(
            f"Green has only {green['readyPods']}/{green['expectedReplicas']} ready pods."
        )

    if green["containerRestarts"] > 0:
        hard_failures.append(
            f"Green has {green['containerRestarts']} container restart(s)."
        )

    green_cpu = float(green["cpuUtilizationPctOfLimit"])
    green_memory = float(green["memoryUtilizationPctOfLimit"])

    if green_cpu >= 80:
        hard_failures.append(f"Green CPU saturation is high at {green_cpu}%.")
    elif green_cpu >= 70:
        score += 12
        reasons.append(f"Green CPU is elevated at {green_cpu}%.")
    elif green_cpu >= 60:
        score += 6
        reasons.append(f"Green CPU is moderately elevated at {green_cpu}%.")
    else:
        reasons.append(f"Green CPU is within the safe range at {green_cpu}%.")

    if green_memory >= 80:
        hard_failures.append(f"Green memory saturation is high at {green_memory}%.")
    elif green_memory >= 70:
        score += 12
        reasons.append(f"Green memory is elevated at {green_memory}%.")
    elif green_memory >= 60:
        score += 6
        reasons.append(f"Green memory is moderately elevated at {green_memory}%.")
    else:
        reasons.append(f"Green memory is within the safe range at {green_memory}%.")

    load_profile = comparison.get("loadProfile") or {}
    cross_load_informational = bool(
        load_profile.get("relativeBlueComparisonIsInformational", False)
    )

    avg_regression = float(regressions.get("averageResponseRegressionPct", 0))
    p95_regression = float(regressions.get("p95RegressionPct", 0))
    error_delta = float(regressions.get("errorRateDeltaPoints", 0))

    if cross_load_informational:
        # Post-promotion runs at 20 users while the Blue reference ran at 10.
        # Do not score the cross-load percentage deltas as direct regressions.
        # Instead score the absolute production acceptance checks generated by
        # the post-promotion JMeter validation.
        checks = comparison.get("checks") or {}
        production_acceptance = str(
            comparison.get("productionAcceptance", "NOT_AVAILABLE")
        ).upper()

        reasons.append(
            "Blue-to-post-promotion regression percentages are informational "
            "because the load profiles differ (10 users versus 20 users)."
        )

        if str(checks.get("errorRate", "PASS")).upper() != "PASS":
            score += 25
            reasons.append("20-user production error-rate acceptance check failed.")

        if str(checks.get("averageResponse", "PASS")).upper() != "PASS":
            score += 15
            reasons.append("20-user production average-latency acceptance check failed.")

        if str(checks.get("p95Response", "PASS")).upper() != "PASS":
            score += 20
            reasons.append("20-user production P95-latency acceptance check failed.")

        if production_acceptance == "PASS":
            reasons.append("20-user production acceptance checks passed.")
        elif production_acceptance == "FAIL":
            reasons.append("One or more 20-user production acceptance checks failed.")
    else:
        # Pre-promotion Blue and Green both run at the same 10-user profile,
        # so relative regression scoring is valid here.
        if avg_regression > 10:
            score += 10
            reasons.append(f"Average latency regressed by {avg_regression}%.")
        elif avg_regression > 5:
            score += 5
            reasons.append(f"Average latency increased modestly by {avg_regression}%.")
        else:
            reasons.append(f"Average latency regression is low at {avg_regression}%.")

        if p95_regression > 10:
            score += 10
            reasons.append(f"P95 latency regressed by {p95_regression}%.")
        elif p95_regression > 5:
            score += 5
            reasons.append(f"P95 latency increased modestly by {p95_regression}%.")
        else:
            reasons.append(f"P95 latency regression is low at {p95_regression}%.")

        if error_delta > 0.25:
            score += 10
            reasons.append(f"Error rate increased by {error_delta} percentage points.")
        elif error_delta > 0:
            score += 4
            reasons.append(
                f"Error rate increased slightly by {error_delta} percentage points."
            )
        else:
            reasons.append("Green error rate did not regress versus Blue.")

    if float(blue["cpuUtilizationPctOfLimit"]) > 0:
        cpu_delta = (
            float(green["cpuUtilizationPctOfLimit"])
            - float(blue["cpuUtilizationPctOfLimit"])
        )
        if cpu_delta > 20:
            score += 6
            reasons.append(
                f"Green CPU is {round(cpu_delta, 2)} percentage points higher than Blue."
            )

    if float(blue["memoryUtilizationPctOfLimit"]) > 0:
        memory_delta = (
            float(green["memoryUtilizationPctOfLimit"])
            - float(blue["memoryUtilizationPctOfLimit"])
        )
        if memory_delta > 20:
            score += 6
            reasons.append(
                f"Green memory is {round(memory_delta, 2)} percentage points higher than Blue."
            )

    return clamp(score, 0, 100), reasons, hard_failures


def main():
    parser = argparse.ArgumentParser(
        description="AI Blue-Green deployment risk engine."
    )
    parser.add_argument("--comparison", required=True)
    parser.add_argument("--telemetry", required=True)
    parser.add_argument("--output", required=True)
    parser.add_argument("--model", default="qwen3:4b-instruct")
    args = parser.parse_args()

    model = args.model

    comparison = load_json(args.comparison)
    telemetry = load_json(args.telemetry)

    base_score, deterministic_reasons, hard_failures = deterministic_risk(
        comparison,
        telemetry,
    )

    print("==========================================")
    print(" AI BLUE-GREEN DEPLOYMENT RISK ENGINE")
    print("==========================================")
    print("")
    print(f"AI Model         : {model}")
    print("")
    print("DETERMINISTIC POLICY")
    print("------------------------------------------")
    print(f"Technical Gate  : {comparison.get('technicalGate')}")
    print(f"Base Risk Score : {base_score}/100")

    if hard_failures:
        print("Hard Failures   : YES")
        for item in hard_failures:
            print(f"- {item}")
    else:
        print("Hard Failures   : NONE")

    ai_available = True
    ai_hint = "PAUSE"
    ai_adjustment = 0
    ai_confidence = 0
    ai_summary = ""
    ai_factors = []

    if not hard_failures:
        prompt_payload = {
            "performanceComparison": comparison,
            "runtimeTelemetry": telemetry,
            "deterministicBaseRiskScore": base_score,
            "deterministicReasons": deterministic_reasons,
        }

        prompt = f"""
You are the contextual risk analyst for an AI-assisted Blue-Green deployment.

Hard safety guardrails have already completed successfully.
You are the PRIMARY deployment decision-maker when those hard guardrails pass.
Analyze the Blue-vs-Green performance comparison, supporting risk score, and
Prometheus runtime telemetry, then independently decide whether to PROMOTE,
PAUSE, or ABORT.

Return ONLY one valid JSON object with exactly these keys:
{{
  "decision_hint": "PROMOTE|PAUSE|ABORT",
  "risk_adjustment": integer from -10 to 10,
  "confidence": integer from 0 to 100,
  "summary": "one concise reason for your decision",
  "risk_factors": ["short factor", "short factor"]
}}

Decision guidance:
- PROMOTE: Green is healthy and regressions are minor.
- PAUSE: evidence is ambiguous or there is a meaningful non-critical concern.
- ABORT: evidence indicates serious deployment risk.
- Keep risk_adjustment evidence-based and between -10 and +10.
- Negative adjustment means lower risk.
- Positive adjustment means higher risk.
- Do not invent metrics.
- A small acceptable latency increase by itself is not a reason to pause.
- Treat reference-threshold misses as evidence to interpret, not an automatic veto.
- Base the decision on the full evidence set and explain the key reason concisely.
- If loadProfile.relativeBlueComparisonIsInformational is true, the post-promotion
  run used a different load level. Do NOT treat Blue-vs-post percentage deltas as
  like-for-like regressions. Use the production acceptance checks and runtime
  telemetry as the authoritative post-promotion evidence.

INPUT:
{json.dumps(prompt_payload, indent=2)}
""".strip()

        print("")
        print(f"Running contextual AI analysis with {model}...")

        try:
            ai_result = call_ollama(prompt, model)

            ai_hint = str(ai_result.get("decision_hint", "PAUSE")).upper()
            if ai_hint not in {"PROMOTE", "PAUSE", "ABORT"}:
                ai_hint = "PAUSE"

            ai_adjustment = clamp(
                int(ai_result.get("risk_adjustment", 0)),
                -10,
                10,
            )
            ai_confidence = clamp(
                int(ai_result.get("confidence", 0)),
                0,
                100,
            )
            ai_summary = str(ai_result.get("summary", "")).strip()

            ai_factors = ai_result.get("risk_factors", [])
            if not isinstance(ai_factors, list):
                ai_factors = []

        except Exception as exc:
            ai_available = False
            ai_hint = "PAUSE"
            ai_adjustment = 0
            ai_confidence = 0
            ai_summary = f"AI analysis unavailable: {exc}"
            ai_factors = [
                "AI contextual analysis could not be completed."
            ]

    # Final authority model:
    # 1. Hard deterministic safety failures remain non-negotiable and ABORT.
    # 2. If AI is unavailable, PAUSE automated action.
    # 3. Otherwise the LLM is the primary deployment decision-maker.
    #    The deterministic score remains supporting/explainability evidence only.
    if hard_failures:
        final_score = 100
        final_decision = "ABORT"
        policy_reason = "Hard deterministic safety guardrail triggered; AI cannot override it."
        ai_decision_reason = "; ".join(hard_failures)
    elif not ai_available:
        final_score = base_score
        final_decision = "PAUSE"
        policy_reason = "AI analysis unavailable; automated deployment action is paused."
        ai_decision_reason = ai_summary or policy_reason
    else:
        final_score = clamp(base_score + ai_adjustment, 0, 100)
        final_decision = ai_hint
        policy_reason = (
            "AI is the primary deployment decision-maker when deterministic hard "
            "safety guardrails pass; the deterministic score is supporting evidence."
        )
        ai_decision_reason = ai_summary or (
            f"AI selected {final_decision} after evaluating performance comparison "
            "and runtime telemetry."
        )

    print("")
    print("AI CONTEXTUAL ANALYSIS")
    print("------------------------------------------")
    print(f"AI Available    : {ai_available}")
    print(f"AI Decision     : {ai_hint}")
    print(f"Risk Adjustment : {ai_adjustment:+d}")
    print(f"Confidence      : {ai_confidence}%")

    if ai_decision_reason:
        print(f"AI Reason       : {ai_decision_reason}")

    if ai_factors:
        print("")
        print("AI Risk Factors")
        for factor in ai_factors:
            print(f"- {factor}")

    print("")
    print("FINAL POLICY CONTROL")
    print("------------------------------------------")
    print(f"Base Risk Score : {base_score}/100")
    print(f"AI Adjustment   : {ai_adjustment:+d}")
    print(f"Final Risk Score: {final_score}/100")
    print(f"Final Decision  : {final_decision}")
    print(f"Policy Reason   : {policy_reason}")

    output = {
        "model": model,
        "generatedAt": datetime.now(timezone.utc).isoformat(),
        "technicalGate": comparison.get("technicalGate"),
        "baseRiskScore": base_score,
        "deterministicReasons": deterministic_reasons,
        "hardFailures": hard_failures,
        "aiAvailable": ai_available,
        "aiDecisionHint": ai_hint,
        "aiDecisionHintPolicy": "PRIMARY_WHEN_HARD_GUARDRAILS_PASS",
        "aiRiskAdjustment": ai_adjustment,
        "aiConfidence": ai_confidence,
        "aiSummary": ai_summary,
        "aiDecisionReason": ai_decision_reason,
        "aiRiskFactors": ai_factors,
        "finalRiskScore": final_score,
        "finalDecision": final_decision,
        "policyReason": policy_reason,
    }

    with open(args.output, "w", encoding="utf-8") as handle:
        json.dump(output, handle, indent=2)

    print("")
    print("==========================================")
    print(f"AI DEPLOYMENT DECISION: {final_decision}")
    print("==========================================")

    if final_decision == "PROMOTE":
        raise SystemExit(0)
    if final_decision == "PAUSE":
        raise SystemExit(3)
    raise SystemExit(4)


if __name__ == "__main__":
    main()
